module.exports = {
  managerChannelsTab: '[href="#managerChannels"]',
  add: 'Add',
  channelName:'Please enter a channel name',
  channelRetention:'#channelRetention',
  minimumQualityRate:'#select2-channelMinQualityRate-container i',
  star4:'#select2-channelMinQualityRate-result-wu8k-4 div',
  channelDomainsDrpdwn:'Please select channel domains',
  politics:'Politics',
  create:'Create',
  deleteChannel:'Delete Item',
  confirm:'[data-bb-handler="confirm"]',
  editChannel:'Edit properties',
  updateChannel:'#editPropertiesBtn',
  successMessage:'Success!',
  viewChannel:'//*[@id="managerPrivateChannelsDt"]/tbody/tr[1]/td[3]',
  channelSetting:'Open Channel Settings',
  chooseAUser:'Choose a User',
  selectAllMatches:'Select all matches',
  addUsersBtn:'#addUsersBtn',
  selectAllUser:'#channelUsersDt-selectall',
  disableUserInChannel:'#disablePrivateUserBtn',
  enableChannel:'[title="Enable channel"]',
  unSubscribe:'#unSubscribe',
  filterChannelSettings:'#filterChannelSettings',
  enableUserInChannel:'#enablePrivateUserBtn',
  disableChannel:'[title="Disable channel"]',
  help:'[title="Help"]',
  pauseAllProjects:'[title="Pause all projects"]',
  resumeAllProjects:'[title="Resume all projects"]',
};
