module.exports = {
  managerDashboardTab: '[href="#managerDashboard"]',
  allEntries:'#allEntries',
  filterActiveProjects:'#filterActiveProjects',
  advancedFilterBtn:'#advancedFilterBtn',
  allStatuses:'All Statuses',
  allChannels:'All Channels',
  available:'#select2-selectProjectStatus-result-sy76-1',
  btnApplyFilter:'#btnApplyFilter',
  projectCheckbox:'[type="checkbox"]',
  btnCancelProjects:'#btnCancelProjects',
  active:'#filterActiveProjects',
  btnPauseProjects:'#btnPauseProjects',
  btnUrgentProjects:'#btnUrgentProjects',
  btnDeadlineProjects:'[id="btnDeadlineProjects"]',
  clearCalendar:'//*[@id="editorsDeadlineDatePicker"]/span[2]',
  update:'#updateBtn',
  saveToExcel:'#saveToExcel',
  downloadBtn:'#downloadBtn',
  expandProject:'[class=" details-control"]',
  downloadOriginalSourceFile:'Click to download original source file',
  files:'[href="#files"]',
  viewProjectAnalytics:'//*[@id="managerProjectsDt"]/tbody/tr[1]/td[16]/span',
  userManagementTab:'[data-test-id="userManagementTab"]',
  editorUser:'[value="28550"]',
  disableUser:'#disableVisibilityForSelectedBtn',
  enableUser:'#enableVisibilityForSelectedBtn',
  yes:'[data-bb-handler="confirm"]',
  filterUserManagementDtBtn:'#filterUserManagementDtBtn',
  selectUserRole:'Select user role',
  editor:'[title="Editor"]',
  reviewer:'[title="Reviewer"]',
  translator:'[title="Translator"]',
  submitUserManagementFiltersBtn:'#submitUserManagementFiltersBtn',
  help:'[title="Help"]',
  editProjectProperties:'Edit project properties',
};
