module.exports = {
  templatesTab: '[href="#projectTemplates"]',
  addTemplatesBtn: '[id="addProjectTemplateBtn"]',
  templatesName:'#templateNameInput',
  projectType:'#select2-sourceLanguageInput-container',
  standard:'Standard',
  sourceLanguage:'#select2-sourceLanguageInput-container',
  sourceSearch:'body > span > span > span.select2-search.select2-search--dropdown > input',
  english_en:'#select2-selectSourceLanguage-result-57he-en',
  targetLanguage:"Select target language(s)",
  hindi_hi:'#select2-selectTargetLanguage-result-3rml-hi',
  next:'Next',
  channelDrpdwn:'#select2-channelInput-container',
  channelNameInput:'body > span > span > span.select2-search.select2-search--dropdown > input',
  styleGuideDrpdwn:'[placeholder="Select a Style Guide"]',
  review:'#reviewCol',
  batchSizeWC:'#batchSizeInput',
  reviewerDeadlineInput:'#editorDeadlineInput',
  projectRuleTemplatesDrpdwn:'#select2-projectRuleSetInput-container',
  projectRuleTemplateInput:'body > span > span > span.select2-search.select2-search--dropdown > input',
  create:'#finishWizard1692083657CreateNewProjectTemplate',
  deleteRuleTemplates:'//*[@id="managerProjectRuleTemplatesDt"]/tbody/tr[1]/td[9]/span',
  deleteConfigTemplates:'//*[@id="managerProjectTemplatesDt"]/tbody/tr[1]/td[19]/span',
  yes:'Yes',
  projectRuleTemplates:'[href="#projectRuleTemplates"]',
  projectRuleTemplates1:'[data-toggle="tab"]',
  addProjectRuleTemplates:'#addProjectRuleTemplateBtn',
  projectRuleTemplatesName:'#projectRuleTemplateName',
  createProjectTemplate:'#createProjectTemplateBtn',
  editProjectConfigTemplates:'//*[@id="managerProjectTemplatesDt"]/tbody/tr[1]/td[17]/span',
  editProjectRuleTemplates:'//*[@id="managerProjectRuleTemplatesDt"]/tbody/tr[1]/td[7]/span',
};
