module.exports = {
  editorTab: '[id="editorMenu"]',
  setting: '[id="settingsMenu]',
  profileImage:'[id="headerProfileImage"]',
  profileName:'[id="headerProfileName"]',
  logout:'[id="logout"]',
  helpFrame:'id="[launcher"]',
  help:'[data-testid="launcher"]',
  channelTab:'[href="#editorChannels"]',
  channelExpand:'[class=" details-control"]',
  helpChannelButton:'[class="fa fa-question fa-stack-1x fa-inverse"]',
  privateChannelsTab:'[href="#privateChannels"]',
  publicChannelsTab:'[href="#publicChannels"]',
  tooglePrivateChannel:'//*[@id="tblEditorPrivateChannels"]/tbody/tr[1]/td[8]/span',
  tooglePublicChannel:'//*[@id="editorPublicChannels"]/tbody/tr[1]/td[8]/span',
  refreshChannel: '[id="tblEditorPrivateChannelsRefresh"]',
  showEntriesdropdown: '[class="select2-selection__arrow"]',
  allChannel:'All',
  search:'[type="search"]',
};
