import { test } from '@playwright/test';
import { LoginPage } from '../../login/pages/LoginPage';
import { ManagerDocExpressPage } from '../pages/ManagerDocExpressPage';
import { Common } from '../../utils/Common';
import { ManagerDashbordPage } from '../pages/ManagerDashbordPage';
import { EditorDashboardPage } from '../../editorTab/pages/EditorDashboardPage';
import { CommunityPage } from '../../controlPannel/pages/CommunityPage';
import { ManagerChannelPage } from '../pages/ManagerChannelPage';

let loginPage;
let common;
let managerDocExpressPage;
let managerDashbordPage;
let editorDashboardPage;
let communityPage;
let managerChannelPage;

test.describe('Multi Manager Feature (@smoke)', () => {
  test.beforeEach(async ({ page, isMobile }) => {
    loginPage = new LoginPage(page, isMobile);
    common = new Common(page, isMobile);
    managerDocExpressPage = new ManagerDocExpressPage(page, isMobile);
    managerDashbordPage = new ManagerDashbordPage(page, isMobile);
    editorDashboardPage = new EditorDashboardPage(page, isMobile);
    communityPage = new CommunityPage(page, isMobile);
    managerChannelPage = new ManagerChannelPage(page, isMobile);
  });

  test('Validate if admin/Manager can asign multiple manager for a user at the time of user creation', async () => {
    await loginPage.navigate();
    await loginPage.clickOnLoginLink();
    await loginPage.enterEmailAddress('ayaz.hasan+multimanager1@helpshift.com');
    await loginPage.enterPassword('Alliswell@3832');
    await loginPage.clickOnLoginButton();
    await managerDocExpressPage.clickOnManagerDocExpressTab();
    await managerDocExpressPage.clickOnProjectTemplateDrpdwn();
    await managerDocExpressPage.enterProjectTemplateName('MultiManagerTemplate1');
    await managerDocExpressPage.clickOnProjectTemplateNameList('MultiManagerTemplate1');
    await managerDocExpressPage.clickOnNext();
    await common.uploadFile('./resources/10Segments.txt','#statusMessage');
    await managerDocExpressPage.waitForFileToBeUploaded();
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnWorkflowAccordionDrpdwn();
    await managerDocExpressPage.clickOnChannelDrpdwn();
    await managerDocExpressPage.enterChannelName('MultiManagerChannel1');
    await managerDocExpressPage.clickOnChannel('MultiManagerChannel1');
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnLaunchProject();
    await common.wait(30000);
    await managerDashbordPage.clickOnManagerDashboardTab();
    const id1= await managerDocExpressPage.getProjectID();
    await managerDocExpressPage.print(managerDocExpressPage);
    await loginPage.clickOnLogOut();
    await loginPage.clickOnLoginLink();
    await loginPage.enterEmailAddress('ayaz.hasan+multimngrEditor1@helpshift.com');
    await loginPage.enterPassword('Alliswell@3832');
    await loginPage.clickOnLoginButton();
    await editorDashboardPage.clickOnDashboard(); 
    await common.search(id1);
    await common.validateText(id1);
    await loginPage.clickOnLogOut(); 
    await loginPage.clickOnLoginLink();
    await loginPage.enterEmailAddress('ayaz.hasan+multimanager2@helpshift.com');
    await loginPage.enterPassword('Alliswell@3832');
    await loginPage.clickOnLoginButton();
    await managerDocExpressPage.clickOnManagerDocExpressTab();
    await managerDocExpressPage.clickOnProjectTemplateDrpdwn();
    await managerDocExpressPage.enterProjectTemplateName('MultiManagerTemplate2');
    await managerDocExpressPage.clickOnProjectTemplateNameList('MultiManagerTemplate2');
    await managerDocExpressPage.clickOnNext();
    await common.uploadFile('./resources/10Segments.txt','#statusMessage');
    await managerDocExpressPage.waitForFileToBeUploaded();
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnWorkflowAccordionDrpdwn();
    await managerDocExpressPage.clickOnChannelDrpdwn();
    await managerDocExpressPage.enterChannelName('MultiManagerChannel2');
    await managerDocExpressPage.clickOnChannel('MultiManagerChannel2');
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnLaunchProject();
    await common.wait(30000);
    await managerDashbordPage.clickOnManagerDashboardTab();
    const id2= await managerDocExpressPage.getProjectID();
    await managerDocExpressPage.print(managerDocExpressPage);
    await loginPage.clickOnLogOut();
    await loginPage.clickOnLoginLink();
    await loginPage.enterEmailAddress('ayaz.hasan+multimngrEditor1@helpshift.com');
    await loginPage.enterPassword('Alliswell@3832');
    await loginPage.clickOnLoginButton();
    await editorDashboardPage.clickOnDashboard(); 
    await common.search(id2);
    await common.validateText(id2);
  });

  test('Validate if admin/Manager can asign/remove more manager for a user at the time of user edit', async () => {
  //Enable Manager(ayaz.hasan+multimanager1@helpshift.com) for editor(ayaz.hasan+multimngrEditor2@helpshift.com)
    await loginPage.navigate();
    await loginPage.clickOnLoginLink();
    await loginPage.enterEmailAddress('ayhasan@keywordsstudios.com');
    await loginPage.enterPassword('Alliswell@3833');
    await loginPage.clickOnLoginButton();
    await communityPage.clickOnCommunityTab();
    await communityPage.clickOnAllUsers();
    await common.search('ayaz.hasan+multimngrEditor2@helpshift.com',1);
    await communityPage.clickOnEditPropertieForUser28700();
    await communityPage.enterManagerTexBox('28697');
    await communityPage.clickOnMultiManager1();
    await communityPage.ClickOnCreate();
    await loginPage.clickOnLogOut();
    await common.wait(60000);
  //Enable the user in the channel
    await loginPage.clickOnLoginLink();
    await loginPage.enterEmailAddress('ayaz.hasan+multimanager1@helpshift.com');
    await loginPage.enterPassword('Alliswell@3832');
    await loginPage.clickOnLoginButton();
    await managerChannelPage.clickOnManagerChannelTab();
    await managerChannelPage.clickOnChannelSetting();
    await managerChannelPage.clickOnSelectAll();
    await managerChannelPage.clickOnEnableUserInChannelToogle();
    await common.clickOnYes();
  //Create the project by manager(ayaz.hasan+multimanager1@helpshift.com) and validate for editor(ayaz.hasan+multimngrEditor2@helpshift.com)
    await managerDocExpressPage.clickOnManagerDocExpressTab();
    await managerDocExpressPage.clickOnProjectTemplateDrpdwn();
    await managerDocExpressPage.enterProjectTemplateName('MultiManagerTemplate1');
    await managerDocExpressPage.clickOnProjectTemplateNameList('MultiManagerTemplate1');
    await managerDocExpressPage.clickOnNext();
    await common.uploadFile('./resources/10Segments.txt','#statusMessage');
    await managerDocExpressPage.waitForFileToBeUploaded();
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnWorkflowAccordionDrpdwn();
    await managerDocExpressPage.clickOnChannelDrpdwn();
    await managerDocExpressPage.enterChannelName('MultiManagerChannel1');
    await managerDocExpressPage.clickOnChannel('MultiManagerChannel1');
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnLaunchProject();
    await common.wait(30000);
    await managerDashbordPage.clickOnManagerDashboardTab();
    const id1= await managerDocExpressPage.getProjectID();
    await managerDocExpressPage.print(managerDocExpressPage);
    await loginPage.clickOnLogOut();
    await loginPage.clickOnLoginLink();
    await loginPage.enterEmailAddress('ayaz.hasan+multimngrEditor2@helpshift.com');
    await loginPage.enterPassword('Alliswell@3832');
    await loginPage.clickOnLoginButton();
    await editorDashboardPage.clickOnDashboard(); 
    await common.search(id1);
    await common.validateText(id1);
    await loginPage.clickOnLogOut();
  //Remove Manager(ayaz.hasan+multimanager1@helpshift.com) for editor(ayaz.hasan+multimngrEditor2@helpshift.com)
    await loginPage.clickOnLoginLink();
    await loginPage.enterEmailAddress('ayhasan@keywordsstudios.com');
    await loginPage.enterPassword('Alliswell@3833');
    await loginPage.clickOnLoginButton();
    await communityPage.clickOnCommunityTab();
    await communityPage.clickOnAllUsers();
    await common.search('ayaz.hasan+multimngrEditor2@helpshift.com');
    await communityPage.clickOnEditPropertieForUser28700();
    await communityPage.ClickOnRemoveMultiManager1();
    await communityPage.ClickOnCreate();
    await loginPage.clickOnLogOut();
  //Create the project by manager(ayaz.hasan+multimanager1@helpshift.com) and validate for editor(ayaz.hasan+multimngrEditor2@helpshift.com)
    await loginPage.clickOnLoginLink();
    await loginPage.enterEmailAddress('ayaz.hasan+multimanager1@helpshift.com');
    await loginPage.enterPassword('Alliswell@3832');
    await loginPage.clickOnLoginButton();
    await managerDocExpressPage.clickOnManagerDocExpressTab();
    await managerDocExpressPage.clickOnProjectTemplateDrpdwn();
    await managerDocExpressPage.enterProjectTemplateName('MultiManagerTemplate1');
    await managerDocExpressPage.clickOnProjectTemplateNameList('MultiManagerTemplate1');
    await managerDocExpressPage.clickOnNext();
    await common.uploadFile('./resources/10Segments.txt','#statusMessage');
    await managerDocExpressPage.waitForFileToBeUploaded();
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnWorkflowAccordionDrpdwn();
    await managerDocExpressPage.clickOnChannelDrpdwn();
    await managerDocExpressPage.enterChannelName('MultiManagerChannel1');
    await managerDocExpressPage.clickOnChannel('MultiManagerChannel1');
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnNext();
    await managerDocExpressPage.clickOnLaunchProject();
    await common.wait(30000);
    await managerDashbordPage.clickOnManagerDashboardTab();
    const id2= await managerDocExpressPage.getProjectID();
    await managerDocExpressPage.print(managerDocExpressPage);
    await loginPage.clickOnLogOut();
    await loginPage.clickOnLoginLink();
    await loginPage.enterEmailAddress('ayaz.hasan+multimngrEditor2@helpshift.com');
    await loginPage.enterPassword('Alliswell@3832');
    await loginPage.clickOnLoginButton();
    await editorDashboardPage.clickOnDashboard(); 
    await common.validateText('No projects currently available!');
  });
});   
